### ISSUE TITLE
nery: roadmap

### ISSUE THREAD

**Issue by davipatricio** [nery-social/nery#1]
- [ ] Back-end
  - [ ] Rewrite the back-end code to use NestJS instead of hapi.js
  - [ ] Routes
    - **USERS**
    - [ ] `GET /users/@handle or @me` - Return user info (avatar, name, handle) but not posts.
    - [ ] `GET /users/@handle/posts` - Return user posts
    - [ ] `GET /users/@handle/likes?page=1` - Return all the liked posts by the user. Return at least 30 posts per page.
    - [ ] `PATCH /users/@me` - Edits the current user information (bio, name, handle, but not e-mail or password).
    - [ ] `PATCH /users/@me/auth` - Changes the current user e-mail or password.
    - **POSTS**
    - [ ] `POST /posts/create` - Create a new post.
    - [ ] `DELETE /posts/id/delete` - Deletes a post.
    - [ ] `GET /posts/id` - Get a post by id.
    - [ ] `GET /posts/id/comments?pages=1&sort=most-liked` - Get post comments.
    - [ ] `POST /posts/id/comment` - Create a comment on a post.
    - [ ] `POST /posts/id/like` - Likes a post or comment.
    - [ ] `POST /posts/id/unlike` - Removes a like from a post or comment.
    - [ ] `POST /posts/id/retweet` - Retweets a post.
    - [ ] `POST /posts/id/retweet` - Un-retweets a post.
    - **SOCIAL**
    - [ ] `POST /users/@handle/follow` - Follows a user.
    - [ ] `POST /users/@handle/unfollow` - Unfollows a user.
    - **FEED**
    - [ ] `GET /feed?sort=most-liked | recent&page=1`
